In [1]:
import numpy as np

In [2]:
j = complex(0,1)

In [3]:
X = np.array([[0, 1],[1,0]])
X

array([[0, 1],
       [1, 0]])

In [4]:
Y = np.array([[0, -j],[j, 0]])
Y

array([[ 0.+0.j, -0.-1.j],
       [ 0.+1.j,  0.+0.j]])

In [5]:
one = np.array([[1],[0]])
one

array([[1],
       [0]])

In [6]:
zero = np.array([[0],[1]])
zero

array([[0],
       [1]])

In [7]:
zero3 = np.kron(zero,np.kron(zero,zero))

In [8]:
one3 = np.kron(one,np.kron(one,one))

In [9]:
ψ = 1/2*(zero3 + one3)
ψ

array([[0.5],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0.5]])

In [10]:
ψt = np.transpose(ψ)
ψt

array([[0.5, 0. , 0. , 0. , 0. , 0. , 0. , 0.5]])

In [11]:
YY = np.kron(Y,Y)
YY

array([[ 0.+0.j,  0.-0.j,  0.-0.j, -1.+0.j],
       [ 0.+0.j,  0.+0.j,  1.-0.j,  0.-0.j],
       [ 0.+0.j,  1.-0.j,  0.+0.j,  0.-0.j],
       [-1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j]])

In [12]:
YYY = np.kron(Y,YY)
YYY

array([[ 0.+0.j,  0.+0.j,  0.+0.j, -0.+0.j,  0.-0.j, -0.+0.j, -0.+0.j,
         0.+1.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.-0.j,  0.-0.j, -0.-1.j,
        -0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.-0.j, -0.-1.j,  0.-0.j,
        -0.+0.j],
       [-0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+1.j,  0.-0.j,  0.-0.j,
         0.-0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j, -0.-1.j,  0.+0.j,  0.+0.j,  0.+0.j,
        -0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+1.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,
         0.+0.j],
       [ 0.+0.j,  0.+1.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,
         0.+0.j],
       [-0.-1.j,  0.+0.j,  0.+0.j,  0.+0.j, -0.+0.j,  0.+0.j,  0.+0.j,
         0.+0.j]])

In [13]:
ψt*YYY*ψ

array([[ 0.+0.j  ,  0.+0.j  ,  0.+0.j  , -0.+0.j  ,  0.+0.j  , -0.+0.j  ,
        -0.+0.j  ,  0.+0.25j],
       [ 0.+0.j  ,  0.+0.j  ,  0.+0.j  ,  0.+0.j  ,  0.+0.j  ,  0.+0.j  ,
         0.+0.j  , -0.+0.j  ],
       [ 0.+0.j  ,  0.+0.j  ,  0.+0.j  ,  0.+0.j  ,  0.+0.j  ,  0.+0.j  ,
         0.+0.j  , -0.+0.j  ],
       [-0.+0.j  ,  0.+0.j  ,  0.+0.j  ,  0.+0.j  ,  0.+0.j  ,  0.+0.j  ,
         0.+0.j  ,  0.+0.j  ],
       [ 0.+0.j  ,  0.+0.j  ,  0.+0.j  ,  0.+0.j  ,  0.+0.j  ,  0.+0.j  ,
         0.+0.j  , -0.+0.j  ],
       [ 0.+0.j  ,  0.+0.j  ,  0.+0.j  ,  0.+0.j  ,  0.+0.j  ,  0.+0.j  ,
         0.+0.j  ,  0.+0.j  ],
       [ 0.+0.j  ,  0.+0.j  ,  0.+0.j  ,  0.+0.j  ,  0.+0.j  ,  0.+0.j  ,
         0.+0.j  ,  0.+0.j  ],
       [ 0.-0.25j,  0.+0.j  ,  0.+0.j  ,  0.+0.j  , -0.+0.j  ,  0.+0.j  ,
         0.+0.j  ,  0.+0.j  ]])

In [14]:
XY = np.kron(X,Y)
XY

array([[0.+0.j, 0.-0.j, 0.+0.j, 0.-1.j],
       [0.+0.j, 0.+0.j, 0.+1.j, 0.+0.j],
       [0.+0.j, 0.-1.j, 0.+0.j, 0.-0.j],
       [0.+1.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [15]:
XXY = np.kron(X,XY)
XXY

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.-1.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+1.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.-1.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+1.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.-1.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+1.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.-1.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+1.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [16]:
ψt*XXY*ψ

array([[0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  ,
        0.+0.j  , 0.-0.25j],
       [0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  ,
        0.+0.j  , 0.+0.j  ],
       [0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  ,
        0.+0.j  , 0.+0.j  ],
       [0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  ,
        0.+0.j  , 0.+0.j  ],
       [0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  ,
        0.+0.j  , 0.+0.j  ],
       [0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  ,
        0.+0.j  , 0.+0.j  ],
       [0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  ,
        0.+0.j  , 0.+0.j  ],
       [0.+0.25j, 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  ,
        0.+0.j  , 0.+0.j  ]])

In [17]:
YX = np.kron(Y,X)
YX

array([[0.+0.j, 0.+0.j, 0.-0.j, 0.-1.j],
       [0.+0.j, 0.+0.j, 0.-1.j, 0.-0.j],
       [0.+0.j, 0.+1.j, 0.+0.j, 0.+0.j],
       [0.+1.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [18]:
XYX = np.kron(X,YX)
XYX

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.-1.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.-1.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+1.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+1.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.-1.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.-1.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+1.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+1.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [19]:
ψt*XYX*ψ

array([[0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  ,
        0.+0.j  , 0.-0.25j],
       [0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  ,
        0.+0.j  , 0.+0.j  ],
       [0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  ,
        0.+0.j  , 0.+0.j  ],
       [0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  ,
        0.+0.j  , 0.+0.j  ],
       [0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  ,
        0.+0.j  , 0.+0.j  ],
       [0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  ,
        0.+0.j  , 0.+0.j  ],
       [0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  ,
        0.+0.j  , 0.+0.j  ],
       [0.+0.25j, 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  ,
        0.+0.j  , 0.+0.j  ]])

In [20]:
XX = np.kron(X,X)
XX

array([[0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0]])

In [21]:
YXX = np.kron(Y,XX)
YXX

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.-0.j, 0.-0.j, 0.-0.j, 0.-1.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.-0.j, 0.-0.j, 0.-1.j, 0.-0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.-0.j, 0.-1.j, 0.-0.j, 0.-0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.-1.j, 0.-0.j, 0.-0.j, 0.-0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+1.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+1.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+1.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+1.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [22]:
ψt*YXX*ψ

array([[0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  ,
        0.+0.j  , 0.-0.25j],
       [0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  ,
        0.+0.j  , 0.+0.j  ],
       [0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  ,
        0.+0.j  , 0.+0.j  ],
       [0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  ,
        0.+0.j  , 0.+0.j  ],
       [0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  ,
        0.+0.j  , 0.+0.j  ],
       [0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  ,
        0.+0.j  , 0.+0.j  ],
       [0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  ,
        0.+0.j  , 0.+0.j  ],
       [0.+0.25j, 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  , 0.+0.j  ,
        0.+0.j  , 0.+0.j  ]])